name: Deploy to Self-Hosted Server

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Update Repository and Install Dependencies
        run: |
          cd ~/brukerguides  # Adjust this path if necessary
          git pull origin main
          npm install

      - name: Verify Deployment
        run: |
          cd ~/brukerguides
          echo "Latest commit in the repository:"
          git log -1 --oneline

      - name: Notify of Deployment Result
        if: success()
        run: echo "Repository updated and dependencies installed."